
const types = {
    GET_TODOS: "GET_TODOS",
    SET_TODOS: "SET_TODOS",
    ADD_TODO: "ADD_TODO",
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    DELETE_TODO: "DELETE_TODO",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
    TOGGLE_TODO: "TOGGLE_TODO",
    TOGGLE_TODO_SUCCESS: "TOGGLE_TODO_SUCCESS"
}

export default types